# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)

trigger:
- master
- release/*

resources:
  repositories:
    - repository: templates
      type: git
      name: neolution-pipelines/pipeline-templates

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: UseDotNet@2
  displayName: Install .NET Core SDK
  inputs:
    packageType: 'sdk'
    version: '6.x'

- task: gitversion/setup@0
  displayName: Install GitVersion
  inputs:
    versionSpec: '5.x'

- task: gitversion/execute@0
  displayName: Execute GitVersion

- task: PowerShell@2
  displayName: Update Build Number
  inputs:
    targetType: 'inline'
    script: 'Write-Host "##vso[build.updatebuildnumber]$(NuGetVersion)"'

- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '*.sln'
    feedsToUse: 'select'
    vstsFeed: 'dc68f94e-847b-4595-86ba-405d5744b21d'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '*.sln'
    arguments: '--configuration $(BuildConfiguration) /p:Version=$(NuGetVersion)'

- template: testing/unittests.yml@templates

- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    packagesToPack: '**/Neolution.DotNet.Console.csproj'
    nobuild: true
    versioningScheme: byEnvVar
    versionEnvVar: NuGetVersion

- task: DotNetCoreCLI@2
  displayName: 'Push'
  inputs:
    command: push
    publishVstsFeed: 'dc68f94e-847b-4595-86ba-405d5744b21d'

- template: security/whitesource.yml@templates
